"Filed out from Dolphin Smalltalk 7"!

FlatResource subclass: #BinaryResource
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
BinaryResource guid: (GUID fromString: '{8c6d8393-41ef-4208-b372-103a48f67fee}')!
BinaryResource comment: ''!
!BinaryResource categoriesForClass!Unclassified! !
!BinaryResource class methodsFor!

resourceType
	^RT_RCDATA! !
!BinaryResource class categoriesFor: #resourceType!private! !

