"Filed out from Dolphin Smalltalk 7"!

FlatResource subclass: #IconResource
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
IconResource guid: (GUID fromString: '{51f58f25-f30a-4105-887f-6ee444f21458}')!
IconResource comment: ''!
!IconResource categoriesForClass!Unclassified! !
!IconResource class methodsFor!

resourceType
	^RT_ICON! !
!IconResource class categoriesFor: #resourceType!*-in class package!private! !

