"Filed out from Dolphin Smalltalk 7"!

Smalltalk at: #OLEShellDataTransferConstants put: (PoolConstantsDictionary named: #OLEShellDataTransferConstants)!
OLEShellDataTransferConstants at: 'CF_BITMAP' put: 16r2!
OLEShellDataTransferConstants at: 'CF_DIB' put: 16r8!
OLEShellDataTransferConstants at: 'CF_DIBV5' put: 16r11!
OLEShellDataTransferConstants at: 'CF_DIF' put: 16r5!
OLEShellDataTransferConstants at: 'CF_DSPBITMAP' put: 16r82!
OLEShellDataTransferConstants at: 'CF_DSPENHMETAFILE' put: 16r8E!
OLEShellDataTransferConstants at: 'CF_DSPMETAFILEPICT' put: 16r83!
OLEShellDataTransferConstants at: 'CF_DSPTEXT' put: 16r81!
OLEShellDataTransferConstants at: 'CF_ENHMETAFILE' put: 16rE!
OLEShellDataTransferConstants at: 'CF_GDIOBJFIRST' put: 16r300!
OLEShellDataTransferConstants at: 'CF_GDIOBJLAST' put: 16r3FF!
OLEShellDataTransferConstants at: 'CF_HDROP' put: 16rF!
OLEShellDataTransferConstants at: 'CF_LOCALE' put: 16r10!
OLEShellDataTransferConstants at: 'CF_MAX' put: 16r12!
OLEShellDataTransferConstants at: 'CF_METAFILEPICT' put: 16r3!
OLEShellDataTransferConstants at: 'CF_OEMTEXT' put: 16r7!
OLEShellDataTransferConstants at: 'CF_OWNERDISPLAY' put: 16r80!
OLEShellDataTransferConstants at: 'CF_PALETTE' put: 16r9!
OLEShellDataTransferConstants at: 'CF_PENDATA' put: 16rA!
OLEShellDataTransferConstants at: 'CF_PRIVATEFIRST' put: 16r200!
OLEShellDataTransferConstants at: 'CF_PRIVATELAST' put: 16r2FF!
OLEShellDataTransferConstants at: 'CF_RIFF' put: 16rB!
OLEShellDataTransferConstants at: 'CF_SYLK' put: 16r4!
OLEShellDataTransferConstants at: 'CF_TEXT' put: 16r1!
OLEShellDataTransferConstants at: 'CF_TIFF' put: 16r6!
OLEShellDataTransferConstants at: 'CF_UNICODETEXT' put: 16rD!
OLEShellDataTransferConstants at: 'CF_WAVE' put: 16rC!
OLEShellDataTransferConstants at: 'DVASPECT_CONTENT' put: 16r1!
OLEShellDataTransferConstants at: 'DVASPECT_COPY' put: 16r3!
OLEShellDataTransferConstants at: 'DVASPECT_DOCPRINT' put: 16r8!
OLEShellDataTransferConstants at: 'DVASPECT_ICON' put: 16r4!
OLEShellDataTransferConstants at: 'DVASPECT_LINK' put: 16r4!
OLEShellDataTransferConstants at: 'DVASPECT_SHORTNAME' put: 16r2!
OLEShellDataTransferConstants at: 'DVASPECT_THUMBNAIL' put: 16r2!
OLEShellDataTransferConstants at: 'TYMED_ENHMF' put: 16r40!
OLEShellDataTransferConstants at: 'TYMED_FILE' put: 16r2!
OLEShellDataTransferConstants at: 'TYMED_GDI' put: 16r10!
OLEShellDataTransferConstants at: 'TYMED_HGLOBAL' put: 16r1!
OLEShellDataTransferConstants at: 'TYMED_ISTORAGE' put: 16r8!
OLEShellDataTransferConstants at: 'TYMED_ISTREAM' put: 16r4!
OLEShellDataTransferConstants at: 'TYMED_MFPICT' put: 16r20!
OLEShellDataTransferConstants at: 'TYMED_NULL' put: 16r0!
OLEShellDataTransferConstants shrink!
