"Filed out from Dolphin Smalltalk 7"!

OFCBarChart subclass: #OFC3dBarChart
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFC3dBarChart guid: (GUID fromString: '{0e717843-8ee0-4a1c-90b5-c8ace2e74767}')!
OFC3dBarChart comment: ''!
!OFC3dBarChart categoriesForClass!Unclassified! !
!OFC3dBarChart methodsFor!

elementType
	^ #'bar_3d'! !
!OFC3dBarChart categoriesFor: #elementType!constants!public! !

