"Filed out from Dolphin Smalltalk 7"!

OFCChartDecoration subclass: #OFCBackground
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFCBackground guid: (GUID fromString: '{b91aea67-934f-4c98-b52b-78084c90c1e3}')!
OFCBackground comment: ''!
!OFCBackground categoriesForClass!Unclassified! !
!OFCBackground methodsFor!

color: aColorOrHTMLHexString 
	ofcCanvas 
		at: #'bg_colour'
		put: aColorOrHTMLHexString! !
!OFCBackground categoriesFor: #color:!accessing!public! !

