"Filed out from Dolphin Smalltalk 7"!

OFCBarChart subclass: #OFCCylinderChart
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFCCylinderChart guid: (GUID fromString: '{6075a1b6-3677-4aa5-8e5e-7ba12b5eef08}')!
OFCCylinderChart comment: ''!
!OFCCylinderChart categoriesForClass!Unclassified! !
!OFCCylinderChart methodsFor!

elementType
	^ #'bar_cylinder'! !
!OFCCylinderChart categoriesFor: #elementType!constants!public! !

