"Filed out from Dolphin Smalltalk 7"!

OFCBarChart subclass: #OFCGlassBarChart
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFCGlassBarChart guid: (GUID fromString: '{2b51d2b7-c0f6-4ff9-a7f0-3310401126f8}')!
OFCGlassBarChart comment: ''!
!OFCGlassBarChart categoriesForClass!Unclassified! !
!OFCGlassBarChart methodsFor!

elementType
	^ #'bar_glass'! !
!OFCGlassBarChart categoriesFor: #elementType!constants!public! !

