"Filed out from Dolphin Smalltalk 7"!

OFCDottedLineChart subclass: #OFCHollowLineChart
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFCHollowLineChart guid: (GUID fromString: '{135cfdd9-0e7d-419c-8a81-eb98007fdf42}')!
OFCHollowLineChart comment: ''!
!OFCHollowLineChart categoriesForClass!Unclassified! !
!OFCHollowLineChart methodsFor!

elementType
	^ #'line_hollow'! !
!OFCHollowLineChart categoriesFor: #elementType!constants!public! !

