"Filed out from Dolphin Smalltalk 7"!

OFCBarChart subclass: #OFCHorizontalBarChart
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFCHorizontalBarChart guid: (GUID fromString: '{6369f6d6-bd85-435f-809f-7151a96a2bf4}')!
OFCHorizontalBarChart comment: ''!
!OFCHorizontalBarChart categoriesForClass!Unclassified! !
!OFCHorizontalBarChart methodsFor!

elementType
	^ #hbar! !
!OFCHorizontalBarChart categoriesFor: #elementType!constants!public! !

