"Filed out from Dolphin Smalltalk 7"!

OFCAreaChart subclass: #OFCHollowAreaChart
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFCHollowAreaChart guid: (GUID fromString: '{c85f1b32-07a9-40af-9352-17d1ff22ccc9}')!
OFCHollowAreaChart comment: ''!
!OFCHollowAreaChart categoriesForClass!Unclassified! !
!OFCHollowAreaChart methodsFor!

elementType
	^ #'area_hollow'! !
!OFCHollowAreaChart categoriesFor: #elementType!constants!public! !

