"Filed out from Dolphin Smalltalk 7"!

OFCScatterChart subclass: #OFCLineScatterChart
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFCLineScatterChart guid: (GUID fromString: '{ef60ed57-eb6b-4293-90d0-14b0fea2469b}')!
OFCLineScatterChart comment: ''!
!OFCLineScatterChart categoriesForClass!Unclassified! !
!OFCLineScatterChart methodsFor!

elementType
	^ #'scatter_line'! !
!OFCLineScatterChart categoriesFor: #elementType!constants!public! !

!OFCLineScatterChart class methodsFor!

icon
	^Icon fromFile: 'Udo Schneider\Goodies\Resources\OFCDottedLineChart.ico'! !
!OFCLineScatterChart class categoriesFor: #icon!public! !

