"Filed out from Dolphin Smalltalk 7"!

OFCChartValue subclass: #OFCLineValue
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFCLineValue guid: (GUID fromString: '{2c1095f0-2809-420a-b329-e1fa872c7f53}')!
OFCLineValue comment: ''!
!OFCLineValue categoriesForClass!Unclassified! !
!OFCLineValue methodsFor!

value: anInteger
	self propertiesAt: #value put: anInteger ! !
!OFCLineValue categoriesFor: #value:!accessing!public! !

