"Filed out from Dolphin Smalltalk 7"!

OFCAreaChart subclass: #OFCLineAreaChart
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFCLineAreaChart guid: (GUID fromString: '{94210487-c4dd-453a-9c4d-3e7d954dfeda}')!
OFCLineAreaChart comment: ''!
!OFCLineAreaChart categoriesForClass!Unclassified! !
!OFCLineAreaChart methodsFor!

elementType
	^ #'area_line'! !
!OFCLineAreaChart categoriesFor: #elementType!constants!public! !

