"Filed out from Dolphin Smalltalk 7"!

OFCGlassBarChart subclass: #OFCRoundGlassBarChart
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFCRoundGlassBarChart guid: (GUID fromString: '{63c7f979-a5ed-491d-bbbc-5039f5806c03}')!
OFCRoundGlassBarChart comment: ''!
!OFCRoundGlassBarChart categoriesForClass!Unclassified! !
!OFCRoundGlassBarChart methodsFor!

elementType
	^ #'bar_round_glass'! !
!OFCRoundGlassBarChart categoriesFor: #elementType!constants!public! !

