"Filed out from Dolphin Smalltalk 7"!

OFCChartValue subclass: #OFCRadarValue
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFCRadarValue guid: (GUID fromString: '{9a266b55-30bf-4be3-9af4-82a77fba091a}')!
OFCRadarValue comment: ''!
!OFCRadarValue categoriesForClass!Unclassified! !
!OFCRadarValue methodsFor!

value: aNumber 
	self 
		propertiesAt: #value
		put: aNumber! !
!OFCRadarValue categoriesFor: #value:!accessing!public! !

