"Filed out from Dolphin Smalltalk 7"!

OFCChartValue subclass: #OFCStackedBarValue
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFCStackedBarValue guid: (GUID fromString: '{7f8829d7-7aa4-4bf9-b5a8-81dcad45408a}')!
OFCStackedBarValue comment: ''!
!OFCStackedBarValue categoriesForClass!Unclassified! !
!OFCStackedBarValue methodsFor!

tooltip
	self shouldNotImplement!

value: anInteger
	self propertiesAt: #val put: anInteger ! !
!OFCStackedBarValue categoriesFor: #tooltip!accessing!public! !
!OFCStackedBarValue categoriesFor: #value:!accessing!public! !

