"Filed out from Dolphin Smalltalk 7"!

OFCStyledText subclass: #OFCTitle
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFCTitle guid: (GUID fromString: '{6b3febd1-910a-48a5-938f-9673c07542cc}')!
OFCTitle comment: ''!
!OFCTitle categoriesForClass!Unclassified! !
!OFCTitle methodsFor!

elementType
	^ #title! !
!OFCTitle categoriesFor: #elementType!constants!public! !

