"Filed out from Dolphin Smalltalk 7"!

OFCStyledText subclass: #OFCXLegend
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFCXLegend guid: (GUID fromString: '{3ecf863b-aa83-436d-ae59-ce4a044b1954}')!
OFCXLegend comment: ''!
!OFCXLegend categoriesForClass!Unclassified! !
!OFCXLegend methodsFor!

elementType
	^ #'x_legend'! !
!OFCXLegend categoriesFor: #elementType!constants!public! !

