"Filed out from Dolphin Smalltalk 7"!

OFCYAxis subclass: #OFCYAxisRight
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFCYAxisRight guid: (GUID fromString: '{6267b6e5-0355-427a-aa84-6a2c338d8560}')!
OFCYAxisRight comment: ''!
!OFCYAxisRight categoriesForClass!Unclassified! !
!OFCYAxisRight methodsFor!

elementType
	^ #'y_axis_right'! !
!OFCYAxisRight categoriesFor: #elementType!constants!public! !

