"Filed out from Dolphin Smalltalk 7"!

OFCStyledText subclass: #OFCYLegend
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OFCYLegend guid: (GUID fromString: '{4204b71c-8ac9-4ffc-87ab-e4e3f492cc95}')!
OFCYLegend comment: ''!
!OFCYLegend categoriesForClass!Unclassified! !
!OFCYLegend methodsFor!

elementType
	^ #'y_legend'! !
!OFCYLegend categoriesFor: #elementType!constants!public! !

