"Filed out from Dolphin Smalltalk 7"!

Smalltalk at: #PropertyListConstants put: (PoolConstantsDictionary named: #PropertyListConstants)!
PropertyListConstants at: 'kCFBinaryPlistMarkerArray' put: 16rA0!
PropertyListConstants at: 'kCFBinaryPlistMarkerASCIIString' put: 16r50!
PropertyListConstants at: 'kCFBinaryPlistMarkerData' put: 16r40!
PropertyListConstants at: 'kCFBinaryPlistMarkerDate' put: 16r33!
PropertyListConstants at: 'kCFBinaryPlistMarkerDict' put: 16rD0!
PropertyListConstants at: 'kCFBinaryPlistMarkerFalse' put: 16r8!
PropertyListConstants at: 'kCFBinaryPlistMarkerFill' put: 16rF!
PropertyListConstants at: 'kCFBinaryPlistMarkerInt' put: 16r10!
PropertyListConstants at: 'kCFBinaryPlistMarkerNull' put: 16r0!
PropertyListConstants at: 'kCFBinaryPlistMarkerReal' put: 16r20!
PropertyListConstants at: 'kCFBinaryPlistMarkerTrue' put: 16r9!
PropertyListConstants at: 'kCFBinaryPlistMarkerUID' put: 16r80!
PropertyListConstants at: 'kCFBinaryPlistMarkerUnicode16String' put: 16r60!
PropertyListConstants at: 'NSPropertyListBinaryFormat_v1_0' put: 16rC8!
PropertyListConstants at: 'NSPropertyListImmutable' put: 16r0!
PropertyListConstants at: 'NSPropertyListMutableContainers' put: 16r1!
PropertyListConstants at: 'NSPropertyListMutableContainersAndLeaves' put: 16r2!
PropertyListConstants at: 'NSPropertyListOpenStepFormat' put: 16r1!
PropertyListConstants at: 'NSPropertyListXMLFormat_v1_0' put: 16r64!
PropertyListConstants shrink!
